### ISSUE TITLE
Fixed page header messes with anchor links

### ISSUE THREAD

**Issue by wildabeast** [phonegap/phonegap-docs#165]
If you follow an anchor link, for example: http://docs.phonegap.com/references/desktop-app/#supported-platforms, the header will overlay a portion of the content being linked to ... possibly all of it, if it is short content.

Seems to be a well-known issue with fixed headers and I won't fight it if its a won't fix, but seems like there are [possible solutions](http://stackoverflow.com/questions/10732690/offsetting-an-html-anchor-to-adjust-for-fixed-header#answer-13184714).

**Comment by GarthDB** [comment]
We already fixed it on the other PhoneGap.com sites. It is just a matter of applying the correct class to the named anchors. I'll do it.

**Comment by GarthDB** [comment]
After lunch.

**Comment by wildabeast** [comment]
I'm actually still seeing this.

Example http://docs.phonegap.com/phonegap-build/faq/#what-platforms

**Comment by GarthDB** [comment]
I might have grabbed the wrong thing. I'll look into it.

**Comment by GarthDB** [comment]
So the named anchors need to be on the line above the heading, fixing now.

**Comment by wildabeast** [comment]
Still seein it i.e. http://docs.phonegap.com/phonegap-build/configuring/preferences/#deployment-target

:(

**Comment by GarthDB** [comment]
@wildabeast it's using `id`s on tags instead of named anchors. To get it to work properly, you have to use a named anchor on it's own line, `<a name="what-versions" class="anchor"></a>`.

You can see an example in the [FAQ page](https://github.com/phonegap/phonegap-docs/blob/master/docs/4-phonegap-build/7-faq.html.md).
